// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIG918HZ_xjwGF4GdqOn9j2CdeZ_eMI2g',
    appId: '1:605356301232:web:4ae7bd46ded375123a1475',
    messagingSenderId: '605356301232',
    projectId: 'finwise-app-1a295',
    authDomain: 'finwise-app-1a295.firebaseapp.com',
    storageBucket: 'finwise-app-1a295.firebasestorage.app',
    measurementId: 'G-D07QTTZTG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhtjNAzIwo_taJSH9oCKRvABiJwFo8Qas',
    appId: '1:605356301232:android:85f87cbc4bd0f9c93a1475',
    messagingSenderId: '605356301232',
    projectId: 'finwise-app-1a295',
    storageBucket: 'finwise-app-1a295.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBZ-IdLdry13rahu2cA8sEKeBeVol4THA',
    appId: '1:605356301232:ios:15bb0a9d756586c33a1475',
    messagingSenderId: '605356301232',
    projectId: 'finwise-app-1a295',
    storageBucket: 'finwise-app-1a295.firebasestorage.app',
    iosBundleId: 'com.example.finwiseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBZ-IdLdry13rahu2cA8sEKeBeVol4THA',
    appId: '1:605356301232:ios:15bb0a9d756586c33a1475',
    messagingSenderId: '605356301232',
    projectId: 'finwise-app-1a295',
    storageBucket: 'finwise-app-1a295.firebasestorage.app',
    iosBundleId: 'com.example.finwiseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIG918HZ_xjwGF4GdqOn9j2CdeZ_eMI2g',
    appId: '1:605356301232:web:2ac56bce8ca1215e3a1475',
    messagingSenderId: '605356301232',
    projectId: 'finwise-app-1a295',
    authDomain: 'finwise-app-1a295.firebaseapp.com',
    storageBucket: 'finwise-app-1a295.firebasestorage.app',
    measurementId: 'G-1YCJ28ZBD5',
  );
}
